---
# This playbook does a rolling update for all servers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#
# The three roles that apply to the webserver hosts will be applied: common,
# base-apache, and web. So any changes to configuration, package updates, etc,
# will be applied as part of the rolling update process.
#
- hosts: app
  become: true
  serial: 1
  tasks:
  - name: disable the server in haproxy
    haproxy:
      state: disabled 
      backend: app 
      host: "{{ inventory_hostname }}" 
      socket: /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: "{{ query('inventory_hostnames', 'haproxy') }}"

  - include_role:
      name: ansible-role-redhatnordicssa-blog
    vars:
      redhatnordicssa_blog_jekyll_listening_port: 80

  - name: wait for jekyll to come up
    wait_for:
      host: "{{ inventory_hostname }}"
      port: 80 
      state: started 
      timeout: 80

  - name: enable the server in haproxy
    haproxy:
      state: enabled
      backend: app 
      host: "{{ inventory_hostname }}" 
      socket: /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: "{{ query('inventory_hostnames', 'haproxy') }}"
